Repository TcOpenGroup/TcOpen, pull requests merged in 2021-05, with the labels that each got.

#73 Use ENV_VAR instead of paths in properties of the build
  pipelines/build.ps1
Labels: infrastructure

#80 Run actions only if changes are made within this paths
  .github/workflows/main.yml
Labels: infrastructure

#78 Add timeout to gh actions
  .github/workflows/main.yml
  .github/workflows/nightly.yml
Labels: infrastructure

#90 Build script, which just builds the solution
  pipelines/build.ps1
Labels: infrastructure

#97 Various additions to TcoCore
  TcOpen.sln
  src/TcoCore/src/TcoCore.Wpf/TcoTask/VisibleOnTaskState.cs
  src/TcoCore/src/TcoCoreConnector/Properties/Localizations.resx
  src/TcoCore/src/TcoCoreConnector/pex/TcoObject/TcoObject.cs
  src/TcoCore/src/TcoCoreConnector/pex/_internals_/_internals_TcoContext.cs
  src/TcoCore/src/XaeTcoCore/TcoCore/POUs/Prototypes/TcoMessage/TcoMessenger.TcPOU
  src/TcoCore/src/XaeTcoCore/TcoCore/POUs/Prototypes/TcoTask/TcoTask.TcPOU
  src/TcoCore/src/XaeTcoCore/TcoCoreExamples/Examples/Components/fbPiston.TcPOU
  src/TcoCore/src/XaeTcoCore/TcoCoreExamples/Examples/Components/fbPistonMoveTask.TcPOU
  src/TcoCore/src/XaeTcoCore/TcoCoreTests/POUs/MAIN.TcPOU
  src/TcoCore/src/XaeTcoCore/TcoCoreTests/TcoCoreTests.plcproj
  src/TcoCore/src/XaeTcoCore/TcoCoreTests/Tests/TcoTask/PlcExecuted/TcoTaskTestContext.TcPOU
  src/TcoCore/src/XaeTcoCore/TcoCoreTests/Tests/TcoTask/PlcExecuted/eTcoTaskTests.TcDUT
  src/TcoCore/src/XaeTcoCore/XaeTcoCore.tsproj
  src/TcoCore/tests/TcoCoreUnitTests/PlcExectutedTests/TcoTaskTests.cs
  src/TcoCore/tests/TcoCoreUnitTests/TcoMessengerTests.cs
Labels: enhancement, initial-development, testing

#109 package updates 1.11.1-nightly.482 + retries on some steps of the build script
  README.md
  pipelines/build.ps1
  src/Tc.Prober/src/Tc.Prober/Tc.Prober.csproj
  src/Tc.Prober/tests/PlcTcProberTestsConnector/PlcTcProberTestsConnector.csproj
  src/Tc.Prober/tests/Tc.ProberTest/Tc.ProberTest.csproj
  src/Tc.Prober/tests/TcProber/TcProber.tsproj
  src/TcoApplicationExamples/XaeAppExamples/XaeAppExamples.tsproj
  src/TcoCore/src/TcoCore.Wpf/TcoCore.Wpf.csproj
  src/TcoCore/src/TcoCoreConnector/TcoCoreConnector.csproj
  src/TcoCore/src/XaeTcoCore/XaeTcoCore.tsproj
  src/TcoCore/tests/TcoDummyTest/TcoDummyTest.csproj
  src/TcoDrivesBeckhoff/src/XaeTcoDrivesBeckhoff/XaeTcoDrivesBeckhoff.tsproj
  src/TcoElements/src/XAE/XAE/XAETcoElements.tsproj
  src/TcoIoBeckhoff/src/TcoIoBeckhoff.Wpf/TcoIoBeckhoff.Wpf.csproj
  src/TcoIoBeckhoff/src/TcoIoBeckhoffConnector/TcoIoBeckhoffConnector.csproj
  src/TcoIoBeckhoff/src/XaeTcoIoBeckhoff/XaeTcoIoBeckhoff.tsproj
  src/TcoPneumatics/src/TcoPneumatics.Wpf/TcoPneumatics.Wpf.csproj
  src/TcoPneumatics/src/TcoPneumaticsConnector/TcoPneumaticsConnector.csproj
  src/TcoPneumatics/src/XaeTcoPneumatics/XaeTcoPneumatics.tsproj
  src/TcoPneumatics/tests/Sandbox/PlcOpen.Wpf.Sandbox/TcoPneumatics.Wpf.Sandbox.csproj
  src/TcoPneumatics/tests/TcoPneumaticsTestsConnector/TcoPneumaticsTestsConnector.csproj
  src/librarytemplate/src/XAE/XAE/XAEPlcTemplate.tsproj
Labels: infrastructure

#121 Create branch and PR on issue
  .github/issue-branch.yml
  .github/workflows/create_issue.yml
Labels: infrastructure

#134 Use PAT to push to documentation repo.
  .github/workflows/docu.yml
Labels: bug, infrastructure
